### ISSUE TITLE
JSON.parse throws error if response isn't valid json string

### ISSUE THREAD

**Issue by lgeiger** [jupyter/jupyter-js-utils#48]
[This line](https://github.com/jupyter/jupyter-js-utils/blob/master/src/index.ts#L283) throws an error if you try connecting to a wrong url.

To reproduce this issue try connecting to https://tmp54.tmpnb.org/user/ which will return `html` rather than a valid `json` string. The full trackeback is:

``` javascript
SyntaxError: Unexpected token <
    at Object.parse (native)
    at [object Object].req.onload (/Users/lukasgeiger/code/hydrogen/node_modules/jupyter-js-services/node_modules/jupyter-js-utils/lib/index.js:166:33)
    at [object Object].dispatchEvent (/Users/lukasgeiger/code/hydrogen/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/Users/lukasgeiger/code/hydrogen/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:614:14)
    at IncomingMessage.<anonymous> (/Users/lukasgeiger/code/hydrogen/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:465:9)
    at process._tickCallback (node.js:379:17)
```

**Comment by sccolbert** [comment]
I'd say that's behaving as expected. The line above indicates you've told it that the request will return JSON:
https://github.com/jupyter/jupyter-js-utils/blob/master/src/index.ts#L282

**Comment by lgeiger** [comment]
Maybe I posted this issue in the wrong repo. I'm using [listRunningSessions](https://github.com/jupyter/jupyter-js-services/blob/2169d19/src/session.ts#L198) from `jupyter-js-services` and think this shouldn't throw an uncaught error.

**Comment by sccolbert** [comment]
In that case, the `tmpnb` server is violating the API contract:
https://github.com/jupyter/jupyter-js-services/blob/2169d19/src/session.ts#L191

```
  /sessions:
    get:
      summary: List available sessions
      tags:
        - sessions
      responses:
        200:
          description: List of current sessions
          schema:
            type: array
            items:
              $ref: '#/definitions/Session'
```

**Comment by sccolbert** [comment]
So, I'd saying throwing is the correct action here.

**Comment by sccolbert** [comment]
cc @blink1073

**Comment by blink1073** [comment]
Agreed, we are expecting the response to match the one described in https://github.com/jupyter/notebook/blob/master/notebook/services/api/api.yaml.   The existing notebook expects the returned value to be of "json" type as well: https://github.com/jupyter/notebook/blob/master/notebook/static/services/sessions/session.js#L83.

**Comment by jasongrout** [comment]
Agreed that it is expected behavior.

**Comment by lgeiger** [comment]
I understand. Thanks for your help!
